<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; margin: 20px; color: #333; }
        header { text-align: center; margin-bottom: 20px; }
        header h1 { margin: 0; font-size: 24px; }
        header p { margin: 2px 0; font-size: 14px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ccc; padding: 6px; text-align: center; font-size: 12px; }
        th { background-color: #007bff; color: #fff; font-weight: bold; }
        tbody tr:nth-child(even) { background-color: #f2f2f2; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; color: #fff; font-size: 11px; }
        .bg-success { background-color: #28a745; }
        .bg-warning { background-color: #ffc107; color: #212529; }
        .bg-danger { background-color: #dc3545; }
        .bg-secondary { background-color: #6c757d; }
        .remarks { text-align: left; padding-left: 5px; }
    </style>
</head>
<body>
    <header>
        <h1>Municipality Attendance Report</h1>
        <p>{{ now()->format('F d, Y') }}</p>
    </header>

    <table>
        <thead>
            <tr>
                <th>Driver Name</th>
                <th>Barangay</th>
                <th>Pickup Date</th>
                <th>Time In</th>
                <th>Time Out</th>
                <th>Hours Worked</th>
                <th>Status</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($attendance as $att)
                @php
                    $hoursWorked = '-';
                    $remarks = '-';
                    if ($att->time_in && $att->time_out) {
                        $hoursWorked = number_format(\Carbon\Carbon::parse($att->time_in)->floatDiffInHours(\Carbon\Carbon::parse($att->time_out)), 2);
                    }

                    // Determine remarks
                    if ($att->status == 'Present') {
                        $remarks = 'On Time';
                    } elseif ($att->status == 'Late') {
                        $remarks = 'Late Arrival';
                    } elseif ($att->status == 'Absent') {
                        $remarks = 'Did Not Attend';
                    }
                @endphp
                <tr>
                    <td>{{ $users->firstWhere('id', $att->user_id)->name ?? 'Unknown' }}</td>
                    <td>{{ $locations->firstWhere('id', $att->location_id)->location ?? 'Unknown' }}</td>
                    <td>{{ $att->pickupSession ?? '-' }}</td>
                    <td>{{ $att->time_in ? \Carbon\Carbon::parse($att->time_in)->format('Y-m-d H:i:s') : '-' }}</td>
                    <td>{{ $att->time_out ? \Carbon\Carbon::parse($att->time_out)->format('Y-m-d H:i:s') : '-' }}</td>
                    <td>{{ $hoursWorked }}</td>
                    <td>
                        @switch($att->status)
                            @case('Present')
                                <span class="badge bg-success">Present</span>
                                @break
                            @case('Late')
                                <span class="badge bg-warning">Late</span>
                                @break
                            @case('Absent')
                                <span class="badge bg-danger">Absent</span>
                                @break
                            @default
                                <span class="badge bg-secondary">{{ $att->status }}</span>
                        @endswitch
                    </td>
                    <td class="remarks">{{ $remarks }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <footer style="margin-top: 30px; text-align: center; font-size: 11px; color: #555;">
        Generated by Municipality Attendance System
    </footer>
</body>
</html>
